###
POST http://localhost:8080/api/member/login
Content-Type: application/x-www-form-urlencoded

username = suwan1 &
password = suwan

###
POST http://localhost:8080/api/member/refresh
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJzb2NpYWwiOmZhbHNlLCJwdyI6IiQyYSQxMCRsWHRCQUpUSUVjaW5wcjY3dkNQVGxPLnYxd09vVUQuTWZZaGhGYUVRWldoQlZGWkFidHR3eSIsIm5pY2tuYW1lIjoidXNlcjEiLCJyb2xlTmFtZXMiOlsiVVNFUiJdLCJlbWFpbCI6InN1d2FuMSIsImlhdCI6MTcxMDkwOTEyOCwiZXhwIjoxNzEwOTA5MTg4fQ.CaWGWRZWE711akf4gIGt3AZ34IT9GUpkDRbHYgpHy6Kypjdjd6DezQT96d6n2qRl

refreshToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJzb2NpYWwiOmZhbHNlLCJwdyI6IiQyYSQxMCRsWHRCQUpUSUVjaW5wcjY3dkNQVGxPLnYxd09vVUQuTWZZaGhGYUVRWldoQlZGWkFidHR3eSIsIm5pY2tuYW1lIjoidXNlcjEiLCJyb2xlTmFtZXMiOlsiVVNFUiJdLCJlbWFpbCI6InN1d2FuMSIsImlhdCI6MTcxMDkwOTEyOCwiZXhwIjoxNzEwOTA5MTg4fQ.CaWGWRZWE711akf4gIGt3AZ34IT9GUpkDRbHYgpHy6Kypjdjd6DezQT96d6n2qRl




#eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJzb2NpYWwiOmZhbHNlLCJwdyI6IiQyYSQxMCRsWHRCQUpUSUVjaW5wcjY3dkNQVGxPLnYxd09vVUQuTWZZaGhGYUVRWldoQlZGWkFidHR3eSIsIm5pY2tuYW1lIjoidXNlcjEiLCJyb2xlTmFtZXMiOlsiVVNFUiJdLCJlbWFpbCI6InN1d2FuMSIsImlhdCI6MTcxMDkwODU1OCwiZXhwIjoxNzEwOTA5MTU4fQ.m5dBsxJxLwhfR8dmO5pjOcutwbRKzesg9iVv-lGh3iKmq7UMA1L3eGY-HOGjvAbo",





### Send POST request with body as parameters
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: application/x-www-form-urlencoded

id = 999 &
value = content &
fact = IntelliJ %+ HTTP Client %= <3

### 카카오 api서버 호출
GET http://localhost:8080/api/member/kakao?accessToken=872z596OPPrRnzQ6k3UrD0tGdjhF4Yk72JcKPXWcAAABjpS9RnoBl6J2VXah6g

### 카카오 그냥 쌩으로,
GET https://kapi.kakao.com/v2/user/me
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer C3FN1rVjQJXRFJ1cBHjX7w3-PXw_IIAEDwcKKiURAAABjpUUOc4Bl6J2VXah6g