###
GET http://localhost:8080/api/products/12
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJzb2NpYWwiOmZhbHNlLCJwdyI6IiQyYSQxMCRsWHRCQUpUSUVjaW5wcjY3dkNQVGxPLnYxd09vVUQuTWZZaGhGYUVRWldoQlZGWkFidHR3eSIsIm5pY2tuYW1lIjoidXNlcjEiLCJyb2xlTmFtZXMiOlsiVVNFUiJdLCJlbWFpbCI6InN1d2FuMSIsImlhdCI6MTcxMDg5MzM2OSwiZXhwIjoxNzEwOTc5NzY5fQ.JGZqrDlcbKBEH6mdYPXkX2qH8JY4EKfXLJc-erelu_RN5qVGPflZiuFy477eVLV2













