spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/suwanreact?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/suwanreact?serverTimezone=Asia/Seoul
    username: react
    password: react

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

com:
  learn:
    learnreact:
      upload:
        path: upload